# NUMPY

In [2]:
import sys
import numpy as np

## Creating Numpy Arrays from Python List

In [5]:
np.array([1,2,3,4])
#Khởi tạo 

array([1, 2, 3, 4])

In [7]:
np.array([3.14, 2, 3, 4])

array([3.14, 2.  , 3.  , 4.  ])

In [9]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [11]:
# nested lists result in multi-dimensional arrays
# danh sách lồng nhau dẫn đến mảng đa chiều
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Array from Scratch: 
### zeros, ones, full, arange, linspace

In [23]:
#np.zeros() : Tạo mảng các phần tử bằng 0 với size = 10 
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
# Create a 3x5 floating-point array filled with ones
# Tạo một mảng dấu phẩy động 3x5 chứa đầy các mảng
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
# Create a 3x5 array filled with 3.14
# Tạo một mảng 3x5 chứa đầy 3,14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [29]:
#Tạo một mảng chứa đầy một chuỗi tuyến tính
# Bắt đầu từ 0, kết thúc ở 20, tăng dần 2
# (điều này tương tự như hàm range() có sẵn)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
# Tạo một mảng gồm năm giá trị cách đều nhau từ 0 đến 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Random

In [38]:
np.random.seed(0)  
# seed for reproducibility
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [40]:
# Tạo một mảng 3x3 gồm các giá trị ngẫu nhiên có phân phối chuẩn
# với giá trị trung bình là 0 và độ lệch chuẩn là 1
np.random.normal(0, 1, (3, 3))

array([[ 1.26611853, -0.50587654,  2.54520078],
       [ 1.08081191,  0.48431215,  0.57914048],
       [-0.18158257,  1.41020463, -0.37447169]])

In [42]:
#numpy.random.random: đối số hình dạng là một bộ dữ liệu duy nhất.
np.random.random((3,5))

np.random.rand(3,5)

array([[0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672],
       [0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077],
       [0.57019677, 0.43860151, 0.98837384, 0.10204481, 0.20887676]])

In [44]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.eye(3, dtype='int8')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [54]:
# Tạo một mảng 4 số nguyên chưa được khởi tạo
# Các giá trị sẽ là bất kỳ giá trị nào đã tồn tại ở vị trí bộ nhớ đó
np.empty(4)

array([0.25, 0.5 , 0.75, 1.  ])